version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: rentx_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
      
  # app: 
  #   build: .
  #   container_name: rentx_app
  #   restart: always
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database_ignite
  #   depends_on: 
  #     - database_ignite
    
volumes:
  pgdata:
    driver: local