version: "3.7"

services:
  database_ignite:
    image: postgres
    container_name: rentx_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks: 
      - backend
  app: 
    build: .
    container_name: rentx_app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks: 
      - backend
    links:
      - "database_ignite:database"

volumes:
  pgdata:
    driver: local
  
networks: 
  backend:
    driver: bridge